package com.example.tangogo.utils

object Routes {
    const val WELCOME = "welcome"
    const val LOGIN = "login"
    const val REGISTER = "register"
    const val DASHBOARD = "dashboard"
    const val LESSON_HIRAGANA = "hiragana"
    const val LESSON_HIRAGANA2 = "hiragana2"
    const val LESSON_KATAKANA = "lesson_katakana"
    const val HIRAGANA_CHART = "hiragana_chart"
    const val A_HIRAGANA_MEMORY = "a_hiragana_memory"
    const val A_HIRAGANA_MNEMONIC = "a_hiragana_mnemonic"
    const val A_HIRAGANA_STROKE = "a_hiragana_draw"
    const val A_HIRAGANA_WRITE = "a_hiragana_write"
    const val STEP_COUNTER = "step_counter"
    const val ACTIVITY_LOG = "activity_log"
    const val WATER_INTAKE = "water_intake"
    const val NUTRI_GO = "nutri_go"
    const val ADD_MEAL = "add_meal"
    const val ADD_ACTIVITY = "add_activity"
    const val BMI_WELCOME = "bmi_welcome"
    const val DAILY_WATER_INTAKE = "water_intake"
    const val WATER_INTAKE_WELCOME = "water_intake_welcome"
    const val WORKOUT_WELCOME = "workout_welcome"
    const val ACTIVITY_WELCOME = "activity_welcome"
    const val NUTRI_GO_WELCOME = "nutri_go_welcome"
}