package com.example.tangogo.utils

object Routes {
    const val WELCOME = "welcome"
    const val LOGIN = "login"
    const val REGISTER = "register"
    const val DASHBOARD = "dashboard"
    const val LESSON_HIRAGANA101 = "hiragana101"
    const val LESSON_HIRAGANAL1 = "hiraganaL1"
    const val LESSON_HIRAGANAL2 = "hiraganaL2"
    const val LESSON_HIRAGANAQ1 = "hiraganaQ1"
    const val LESSON_HIRAGANAQ2 = "hiraganaQ2"
    const val LESSON_HIRAGANASpeak = "hiraganaSpeak"
    const val LESSON_KATAKANA = "lesson_katakana"

    const val HIRAGANA_CHART = "hiragana_chart"
    const val A_HIRAGANA_MEMORY = "a_hiragana_memory"
    const val A_HIRAGANA_MNEMONIC = "a_hiragana_mnemonic"
    const val A_HIRAGANA_STROKE = "a_hiragana_draw"
    const val A_HIRAGANA_WRITE = "a_hiragana_write"
    const val I_HIRAGANA_MEMORY = "i_hiragana_memory"
    const val I_HIRAGANA_MNEMONIC = "i_hiragana_mnemonic"
    const val I_HIRAGANA_STROKE = "i_hiragana_draw"
    const val I_HIRAGANA_WRITE = "i_hiragana_write"
    const val U_HIRAGANA_MEMORY = "u_hiragana_memory"
    const val U_HIRAGANA_MNEMONIC = "u_hiragana_mnemonic"
    const val U_HIRAGANA_STROKE = "u_hiragana_draw"
    const val U_HIRAGANA_WRITE = "u_hiragana_write"
    const val E_HIRAGANA_MEMORY = "e_hiragana_memory"
    const val E_HIRAGANA_MNEMONIC = "e_hiragana_mnemonic"
    const val E_HIRAGANA_STROKE = "e_hiragana_draw"
    const val E_HIRAGANA_WRITE = "e_hiragana_write"
    const val O_HIRAGANA_MEMORY = "o_hiragana_memory"
    const val O_HIRAGANA_MNEMONIC = "o_hiragana_mnemonic"
    const val O_HIRAGANA_STROKE = "o_hiragana_draw"
    const val O_HIRAGANA_WRITE = "o_hiragana_write"

    const val KATAKANA_CHART = "katakana_chart"
}